name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Show current version of Xcode
        run: xcodebuild -version      
      - name: Run tests
        run: make test