name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      # Workaround for Xcode 15.x performance regression
      # ref. https://bitrise.io/blog/post/xcode-15-performance-regressions
      - name: Install yeetd
        run: |
            wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
            sudo installer -pkg yeetd-normal.pkg -target /
            yeetd &      
      - name: Show current version of Xcode
        run: xcodebuild -version      
      - name: Run tests
        run: make test